#!/usr/bin/python3
from math import *
from sys import *


def factorize(number):
    if (number % 2 == 0):
        return (2)
    max = isqrt(number) + 1
    for i in range(3, max, 2):
        if (number % i == 0):
            return(i)

if __name__=='__main__':
    f = open(argv[1], "r")
    for line in f:
        n = int(line)
        q = factorize(n)
        p = n // q
        print("{}={}*{}".format(n, p, q))
    f.close()
