#!/usr/bin/python3
from math import *
from sys import *

def ten_times(number, first_prime):
    max = isqrt(number) + 1
    for i in range(first_prime, max, 10):
        if (number % i == 0):
            return (i)
    return (-1)

def factorize(number):
    primes = [3, 7, 11, 19]
    for i in primes:
        factor = ten_times(number, i)
        if (factor != -1):
            return (factor)
    return (1)

if __name__=='__main__':
    if (len(argv) != 2):
        print("Usage: factors <file>")
        exit(-1)
    with open(argv[1], 'r') as f:
        for line in f:
            n = int(line)
            q = factorize(n)
            p = n // q
            print("{:d}={:d}*{:d}".format(n, p, q))
    f.close()
